In [1]:
import numpy as np
import pandas as pd

# Numpy Problems

## 1. Creating Arrays
● Question: Using NumPy, create a 1D array of 20 random integers between 10 and 
50. Then, find the mean and standard deviation of the array. 
● Hint: Use np.random.randint() for creating 1D array.

In [2]:
i = 20
int_list = []
while(i > 0):
    int_list.append(np.random.randint(10,50))
    i -= 1
int_list = np.array(int_list)
print(f'The mean of the random array is {np.mean(int_list)}')
print(f'The standard deviation of the random array is {np.std(int_list):02f}')

The mean of the random array is 33.5
The standard deviation of the random array is 11.368817


## 2. Array Reshaping
● Question: Create a 2D NumPy array of shape (6, 5) filled with random floats 
between 0 and 1. Reshape this array to have shape (5, 6) and print both the original 
and reshaped arrays. 
● Hint: Use np.random.rand() 

In [3]:
i = 30
float_list = []
while(i>0):
    float_list.append(np.random.random())
    i-=1
float_list = np.array(float_list)
array65 = float_list.reshape(6,5)
array56 = array65.reshape(5,6)
print(f'The original array is: \n {array65}\n')
print(f'The reshaped array is: \n {array56}\n')

The original array is: 
 [[0.09606191 0.77829302 0.85717047 0.78120182 0.60641616]
 [0.6274768  0.88403272 0.71021169 0.05379533 0.34849197]
 [0.14651929 0.17637898 0.38131403 0.96794569 0.43630203]
 [0.26707637 0.97631046 0.70255676 0.72786157 0.43136681]
 [0.51446427 0.48002195 0.80003039 0.45298767 0.01572994]
 [0.79519285 0.40638868 0.6832204  0.71776377 0.77462961]]

The reshaped array is: 
 [[0.09606191 0.77829302 0.85717047 0.78120182 0.60641616 0.6274768 ]
 [0.88403272 0.71021169 0.05379533 0.34849197 0.14651929 0.17637898]
 [0.38131403 0.96794569 0.43630203 0.26707637 0.97631046 0.70255676]
 [0.72786157 0.43136681 0.51446427 0.48002195 0.80003039 0.45298767]
 [0.01572994 0.79519285 0.40638868 0.6832204  0.71776377 0.77462961]]



## 3. Array Indexing and Slicing
● Question: Create a 2D array of shape (5, 5) filled with numbers from 1 to 25. 
Extract a subarray that includes rows 2 to 4 and columns 1 to 3. 
● Hint: Use np.arange() and slicing techniques. 

In [4]:
arr_1 = np.arange(1,26)
arr55 = arr_1.reshape(5,5)
arr_24_13 = arr55[2:5,1:4]
print(f'Original array is \n {arr55} \n')
print(f'The sliced array is \n {arr_24_13} \n')

Original array is 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]] 

The sliced array is 
 [[12 13 14]
 [17 18 19]
 [22 23 24]] 



## 4.Array Operations
● Question: Generate two 1D arrays A and B, each containing 10 random integers 
between 1 and 100. Add the arrays together, then multiply the result by 2. Show 
the results of each operation. 
● Hint: Use + for addition and * for multiplication. 

In [5]:
i = 10
int_list1 = []
int_list2 = []
while(i > 0):
    int_list1.append(np.random.randint(1,100))
    int_list2.append(np.random.randint(1,100))
    i -= 1
int_list1 = np.array(int_list1)
print(f'The 1st list is\n {int_list1} \n')
int_list2 = np.array(int_list2)
print(f'The 2nd list is\n {int_list2} \n')
list1plus2 = int_list1 + int_list2
print(f'The sum of lists is\n {list1plus2} \n')
print(f'The sum of list * 2 is\n{list1plus2 * 2}')


The 1st list is
 [58 62 71 87 53 89 54 84 15  1] 

The 2nd list is
 [52 92 72 83 60 25 42 94 53 17] 

The sum of lists is
 [110 154 143 170 113 114  96 178  68  18] 

The sum of list * 2 is
[220 308 286 340 226 228 192 356 136  36]


## 5. Broadcasting
Question: Create a 2D array A of shape (3, 4) filled with random integers between 
1 and 10. Create a 1D array B of shape (4,) with values [1, 2, 3, 4]. Add the 1D array 
to the 2D array and explain how broadcasting works in this case. 

In [6]:
A = np.random.randint(1,10,size = (3,4))
B = np.array([1,2,3,4])
print(f'Array A is \n {A} \n')
print(f'Array B is \n {B} \n')
print(f'Array A + B is \n {A+B} \n')

Array A is 
 [[6 4 4 5]
 [9 1 9 4]
 [1 3 6 9]] 

Array B is 
 [1 2 3 4] 

Array A + B is 
 [[ 7  6  7  9]
 [10  3 12  8]
 [ 2  5  9 13]] 



## 6. Finding Maximum/Minimum Values
● Question: Create a 3x3 matrix of random integers between 1 and 100. Find the 
row with the maximum sum, and then the maximum value in that row. 
● Hint: Use np.sum() and np.argmax(). 

In [7]:
arr33 = np.random.randint(1,100,size = (3,3))
max_sum = 0
temp = 0
print(f'The generated array is \n{arr33}\n')
for line in arr33:
    if np.sum(line) > max_sum:
        temp = line
        max_sum = np.sum(line)
print(f'The row having maximum sum is {temp} and the sum is {max_sum}\n')
print(f'The max value in the row is {temp[np.argmax(temp)]}')


The generated array is 
[[23 32 19]
 [81 98 42]
 [18 91 15]]

The row having maximum sum is [81 98 42] and the sum is 221

The max value in the row is 98


## 7. Linear Algebra
● Question: Create two 2D arrays A and B, both of shape (2, 2), filled with random 
integers. Compute the matrix multiplication of A and B using np.dot(). 
● Hint: Use np.random.randint() and np.dot().

In [8]:
Arr_A = np.random.randint(1,100,size = (2,2))
Arr_B = np.random.randint(1,100,size = (2,2))
Arr_dot = np.dot(Arr_A,Arr_B)
print(f'Array A is \n {Arr_A} \n')
print(f'Array B is \n {Arr_B} \n')
print(f'The dot product is \n {Arr_dot} \n')

Array A is 
 [[14 53]
 [77 98]] 

Array B is 
 [[32 99]
 [44 19]] 

The dot product is 
 [[2780 2393]
 [6776 9485]] 



## 8. Boolean Indexing
● Question: Create an array of shape (6, 6) with random integers between 1 and 50. 
Using boolean indexing, extract all values greater than 25. 
● Hint: Use boolean conditions like array > 25. 

In [9]:
arr_1 = np.random.randint(1,50,size = (6,6))
print('Boolean Indexing:\n',arr_1 > 25,'\n')
print('The values greater than 25 is:')
for row in arr_1:
    for element in row:
        if element >25:
            print(element, end = ',')

Boolean Indexing:
 [[ True False False  True  True False]
 [ True  True False False False  True]
 [ True False False False  True False]
 [False False  True False False False]
 [False False False False  True False]
 [ True False False False False  True]] 

The values greater than 25 is:
36,31,35,43,32,31,32,35,45,37,38,41,

## 9. Statistics
● Question: Create a 5x5 array of random floats between 0 and 1. Calculate the 
median and variance along the columns and rows separately. 
● Hint: Use np.median() and np.var() with the axis parameter. 

In [10]:
arr_ = np.random.rand(5,5)
print(f'The array is \n{arr_}\n')
print(f'The row wise stats are: \n')
for index,line in enumerate(arr_):
    print(f'The median of row {index} is {np.median(line)}')
    print(f'The variance of row {index} is {np.var(line)}\n')
print(f'The column wise stats are: \n')
for i in range(0,5):
    temp = arr_[:,i:i+1]
    print(f'The median of column {i} is {np.median(temp)}')
    print(f'The variance of column {i} is {np.var(temp)}\n')    

The array is 
[[0.54386129 0.47532112 0.65086237 0.20151737 0.95387343]
 [0.20226589 0.00671313 0.83241442 0.13102986 0.69297025]
 [0.89537803 0.1295036  0.80997827 0.94171548 0.92649945]
 [0.15436929 0.70191576 0.87713872 0.92356412 0.1014855 ]
 [0.01801315 0.77086396 0.00257062 0.23573984 0.92014187]]

The row wise stats are: 

The median of row 0 is 0.543861286633523
The variance of row 0 is 0.05984072453729934

The median of row 1 is 0.20226588786291866
The variance of row 1 is 0.10706165820483848

The median of row 2 is 0.8953780258335969
The variance of row 2 is 0.09544288747638477

The median of row 3 is 0.701915764912654
The variance of row 3 is 0.12546457016277618

The median of row 4 is 0.2357398387987263
The variance of row 4 is 0.14767565479093153

The column wise stats are: 

The median of column 0 is 0.20226588786291866
The variance of column 0 is 0.10090301541174977

The median of column 1 is 0.47532111581083625
The variance of column 1 is 0.09215749108626661

The median

## 10. Element-wise Operations
● Question: Generate a 3x3 matrix of random integers between 1 and 10. Perform 
the following element-wise operations: subtract 2 from each element, square each 
element, and compute the reciprocal of each element. 
● Hint: Use standard arithmetic operations and np.reciprocal(). 

In [11]:
arr_random = np.random.randint(1,10,size = (3,3))
arr_sub2 = arr_random -2
arr_square = arr_random**2
arr_reciprocal = (np.reciprocal(arr_random.astype(float)))
print(f'The subtracted array is :\n {arr_sub2}\n')
print(f'The squared array is :\n {arr_square}\n')
print(f'The reciprocal array is :\n {arr_reciprocal}')

The subtracted array is :
 [[4 7 4]
 [7 7 3]
 [4 5 1]]

The squared array is :
 [[36 81 36]
 [81 81 25]
 [36 49  9]]

The reciprocal array is :
 [[0.16666667 0.11111111 0.16666667]
 [0.11111111 0.11111111 0.2       ]
 [0.16666667 0.14285714 0.33333333]]


# Pandas Problems

## 1. Basic Exploration
Load the dataset into a Pandas DataFrame. Display: 
○ The first 10 rows 
○ The total number of rows and columns 
○ Summary statistics for numerical columns

In [12]:
import pandas as pd
import numpy as np
df = pd.read_csv('auto-mpg.csv')

In [13]:
df.head(10) #first 10 rows

mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   
5  15.0          8         429.0        198    4341          10.0          70   
6  14.0          8         454.0        220    4354           9.0          70   
7  14.0          8         440.0        215    4312           8.5          70   
8  14.0          8         455.0        225    4425          10.0          70   
9  15.0          8         390.0        190    3850           8.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino  
5       1           ford galaxie 500  
6       1           chevrolet impala  
7       1          plymouth fury iii  
8       1           pontiac catalina  
9       1         amc ambassador dpl

In [14]:
df.shape # number of rows and columns

(398, 9)

In [15]:
df.describe() #Summary statistics for numerical columns

mpg   cylinders  displacement       weight  acceleration  \
count  398.000000  398.000000    398.000000   398.000000    398.000000   
mean    23.514573    5.454774    193.425879  2970.424623     15.568090   
std      7.815984    1.701004    104.269838   846.841774      2.757689   
min      9.000000    3.000000     68.000000  1613.000000      8.000000   
25%     17.500000    4.000000    104.250000  2223.750000     13.825000   
50%     23.000000    4.000000    148.500000  2803.500000     15.500000   
75%     29.000000    8.000000    262.000000  3608.000000     17.175000   
max     46.600000    8.000000    455.000000  5140.000000     24.800000   

       model year      origin  
count  398.000000  398.000000  
mean    76.010050    1.572864  
std      3.697627    0.802055  
min     70.000000    1.000000  
25%     73.000000    1.000000  
50%     76.000000    1.000000  
75%     79.000000    2.000000  
max     82.000000    3.000000

## 2.Filtering and Indexing
Find all cars manufactured in 1975 with a weight less than 3000. Return the 
DataFrame with selected columns: car_name, weight, and mpg. 

In [16]:
new_df = df[(df['model year'] == 75) & (df['weight'] < 3000)]
new_df = new_df[['car name','weight','mpg']]
print(new_df)

              car name  weight   mpg
167     toyota corolla    2171  29.0
168         ford pinto    2639  23.0
169        amc gremlin    2914  20.0
170      pontiac astro    2592  23.0
171      toyota corona    2702  24.0
172  volkswagen dasher    2223  25.0
173         datsun 710    2545  24.0
174         ford pinto    2984  18.0
175  volkswagen rabbit    1937  29.0
177         audi 100ls    2694  23.0
178        peugeot 504    2957  23.0
179        volvo 244dl    2945  22.0
180          saab 99le    2671  25.0
181   honda civic cvcc    1795  33.0


## 3. Handling Missing Data
Identify if there are any missing values in the dataset. Replace missing values in the 
horsepower column with the column's median. 

In [17]:
df = pd.read_csv('auto-mpg.csv')
df['horsepower'].replace('?', np.nan, inplace=True)
df['horsepower'] = df['horsepower'].astype(float)
median_hp = df['horsepower'].median()
df['horsepower'].fillna(median_hp, inplace=True)


C:\Users\prana\AppData\Local\Temp\ipykernel_3164\2220104091.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['horsepower'].replace('?', np.nan, inplace=True)
C:\Users\prana\AppData\Local\Temp\ipykernel_3164\2220104091.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For ex

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    float64
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64  
 7   origin        398 non-null    int64  
 8   car name      398 non-null    object 
dtypes: float64(4), int64(4), object(1)
memory usage: 28.1+ KB


## 4.Data Transformation
Add a new column power_to_weight_ratio, calculated as horsepower / weight. 

In [19]:
df['power_to_weight_ratio'] = df.horsepower/df.weight

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   mpg                    398 non-null    float64
 1   cylinders              398 non-null    int64  
 2   displacement           398 non-null    float64
 3   horsepower             398 non-null    float64
 4   weight                 398 non-null    int64  
 5   acceleration           398 non-null    float64
 6   model year             398 non-null    int64  
 7   origin                 398 non-null    int64  
 8   car name               398 non-null    object 
 9   power_to_weight_ratio  398 non-null    float64
dtypes: float64(5), int64(4), object(1)
memory usage: 31.2+ KB


In [21]:
df[['power_to_weight_ratio']]

power_to_weight_ratio
0                 0.037100
1                 0.044679
2                 0.043655
3                 0.043694
4                 0.040591
..                     ...
393               0.030824
394               0.024413
395               0.036601
396               0.030095
397               0.030147

[398 rows x 1 columns]

## 5. Group By
Group the cars by origin and calculate the mean mpg for each group. 

In [22]:
mean_mpg_by_origin = df.groupby('origin')['mpg'].mean()
mean_mpg_by_origin.reset_index()

origin        mpg
0       1  20.083534
1       2  27.891429
2       3  30.450633

## 6. Sorting 
Sort the DataFrame by mpg in descending order and display the top 10 cars with 
the highest mpg. 
 


In [23]:
sorted_df = df.sort_values(by='mpg', ascending=False)
top_10_mpg_cars = sorted_df.head(10)
result_df = top_10_mpg_cars[['car name', 'weight', 'mpg']]
result_df

car name  weight   mpg
322                        mazda glc    2110  46.6
329              honda civic 1500 gl    1850  44.6
325             vw rabbit c (diesel)    2085  44.3
394                        vw pickup    2130  44.0
326               vw dasher (diesel)    2335  43.4
244  volkswagen rabbit custom diesel    1985  43.1
309                        vw rabbit    2144  41.5
330             renault lecar deluxe    1835  40.9
324                       datsun 210    2110  40.8
247                   datsun b210 gx    2070  39.4

## 7.Apply Function
Create a new column performance_score using a custom function: 
def performance_score(row): 
return row['mpg'] * row['acceleration'] / row['weight']

In [24]:
def performance_score(row):
    return row['mpg'] * row['acceleration'] / row['weight']

df['performance_score'] = df.apply(performance_score, axis=1)
df['performance_score'].reset_index()

index  performance_score
0        0           0.061644
1        1           0.046710
2        2           0.057625
3        3           0.055928
4        4           0.051754
..     ...                ...
393    393           0.150968
394    394           0.508169
395    395           0.161743
396    396           0.198400
397    397           0.221103

[398 rows x 2 columns]

## 8. Visualization Preparation
Generate a summary DataFrame with:   
○ Average mpg, weight, and horsepower for each model_year. 

In [25]:
summary_df = df.groupby('model year').agg({'mpg': 'mean','weight': 'mean','horsepower': 'mean'}).reset_index()
print(summary_df)

    model year        mpg       weight  horsepower
0           70  17.689655  3372.793103  147.827586
1           71  21.250000  2995.428571  106.553571
2           72  18.714286  3237.714286  120.178571
3           73  17.100000  3419.025000  130.475000
4           74  22.703704  2877.925926   94.203704
5           75  20.266667  3176.800000  101.066667
6           76  21.573529  3078.735294  101.117647
7           77  23.375000  2997.357143  105.071429
8           78  24.061111  2861.805556   99.694444
9           79  25.093103  3055.344828  101.206897
10          80  33.696552  2436.655172   78.586207
11          81  30.334483  2522.931034   81.465517
12          82  31.709677  2453.548387   81.854839


## 9. Exporintg Data
Save a subset of the data containing only mpg, cylinders, horsepower, and weight 
for cars with mpg > 30 into a CSV file named high_mpg_cars.csv. 

In [26]:
high_mpg_cars = df[df['mpg'] > 30]
subset_df = high_mpg_cars[['mpg', 'cylinders', 'horsepower', 'weight']]
subset_df.to_csv('high_mpg_cars.csv', index=False)
print(subset_df.reset_index())

    index   mpg  cylinders  horsepower  weight
0      53  31.0          4        65.0    1773
1      54  35.0          4        69.0    1613
2     129  31.0          4        67.0    1950
3     131  32.0          4        65.0    1836
4     144  31.0          4        52.0    1649
..    ...   ...        ...         ...     ...
80    390  32.0          4        96.0    2665
81    391  36.0          4        84.0    2370
82    394  44.0          4        52.0    2130
83    395  32.0          4        84.0    2295
84    397  31.0          4        82.0    2720

[85 rows x 5 columns]


## 10.Finding Anomalies
Identify potential outliers in the mpg column using the Interquartile Range (IQR) 
method. Specifically:   
● Calculate the IQR for mpg.   
● Define outliers as values less than Q1 - 1.5 * IQR or greater than Q3 + 1.5 * 
IQR.   
● Create a DataFrame of cars classified as outliers, displaying car_name, mpg, 
and model_year.   

In [27]:
Q1 = df['mpg'].quantile(0.25)
Q3 = df['mpg'].quantile(0.75)
IQR = Q3 - Q1
print(f'The IQR is {IQR}\n')
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = df[(df['mpg'] < lower_bound) | (df['mpg'] > upper_bound)]
outliers_df = outliers[['car name', 'mpg', 'model year']]
print(outliers_df.reset_index())

The IQR is 11.5

   index   car name   mpg  model year
0    322  mazda glc  46.6          80
